### ISSUE TITLE
在做PSI时，如果一方运行，另一方不运行。在尝试连接超时时会出现段错误

### ISSUE THREAD

**Issue by Cryptographer63** [secretflow/spu#17]
As shown in the figure below, when doing PSI, if one side is running, the other side is not running. A  **"Aborted (core dumped)"**  occurs when an attempt to connect times out. At the same time, after modifying this problem (that is, modifying the code to ignore the thrown exception), it is easy to cause a **"Aborted (core dumped)"**   when one party continues to not receive data. Guess it was caused by throwing an exception.
![image](https://user-images.githubusercontent.com/76472033/187164221-7259170c-8db3-4ed0-bf9f-c4e1d8c96121.png)

ositioning problem:

1. yasl/link/transport/channel.cc ： 86
2. yasl/yasl/link/context.cc ：141

**Comment by icavan** [comment]
Yes. This is expected behavior.

We do require our users to run both sides in a short time window if using SPU directly. If you wanna make life easier, you could try to call PSI in Secretflow, which will help dispatch MPI PSI codes to both sides simultaneously.

---

BTW, if you do want to play with the core c++ API. The link timeout could be set by calling `void SetRecvTimeout(uint32_t recv_timeout_ms);` in https://github.com/secretflow/yasl/blob/beta/yasl/link/context.h#L163. Our `simple_psi` example just serves as a simple demo for experiencing the core PSI API. You could play and adjust timeout as you needed.

**Comment by Cryptographer63** [comment]
> Yes. This is expected behavior.
> 
> We do require our users to run both sides in a short time window if using SPU directly. If you wanna make life easier, you could try to call PSI in Secretflow, which will help dispatch MPI PSI codes to both sides simultaneously.
> 
> BTW, if you do want to play with the core c++ API. The link timeout could be set by calling `void SetRecvTimeout(uint32_t recv_timeout_ms);` in https://github.com/secretflow/yasl/blob/beta/yasl/link/context.h#L163. Our `simple_psi` example just serves as a simple demo for experiencing the core PSI API. You could play and adjust timeout as you needed.

Thank you for your reply！

Secretflow is too big, I just need the PSI module. Excuse me, why is it designed this way? Are there any real issues to consider?

I'll try using SetRecvTimeout to see if that solves my problem.

I think the C++ API is still very important, after all, these APIs are closer to the bottom layer, and many developers like me can have more room to play.

**Comment by icavan** [comment]
> > Yes. This is expected behavior.
> > We do require our users to run both sides in a short time window if using SPU directly. If you wanna make life easier, you could try to call PSI in Secretflow, which will help dispatch MPI PSI codes to both sides simultaneously.
> > BTW, if you do want to play with the core c++ API. The link timeout could be set by calling `void SetRecvTimeout(uint32_t recv_timeout_ms);` in https://github.com/secretflow/yasl/blob/beta/yasl/link/context.h#L163. Our `simple_psi` example just serves as a simple demo for experiencing the core PSI API. You could play and adjust timeout as you needed.
> 
> Thank you for your reply！
> 
> Secretflow is too big, I just need the PSI module. Excuse me, why is it designed this way? Are there any real issues to consider?
> 
> I'll try using SetRecvTimeout to see if that solves my problem.
> 
> I think the C++ API is still very important, after all, these APIs are closer to the bottom layer, and many developers like me can have more room to play.

We do plan to open source all layers of the SecretFlow stack, including the C++ core API layer. Since we still have lots of pending optimizations waiting for formal security review and open source procedure, you might need to wait for a few months to get better API documentation and performance.

I did not expect you guys will play the c++ core API this quick. Let me know what you need. This might affect some priority decisions for where we should improve first.

**Comment by rivertalk** [comment]
Fixed in latest beta branch, closing...
