### ISSUE TITLE
BeaverTfpUnsafe Reconstruct

### ISSUE THREAD

**Issue by HuifengShrimp** [secretflow/spu#25]
I don't know much about cryptography.  In spu/mpc/beaver/beaver_tfp.cc, I don't understand the operation for the third party to do: 
`  if (lctx_->Rank() == 0) {
    c = tp_.adjustDot(descs, M, N, K);
  }`
In my perspective, two parties first generate random arrays a, b, and c respectively. These random arrays are different for the two parties.  I used to think the c of Rank 1 adding the adjusted c of Rank 0 is the original multiplication result of a and b of Rank 1.  But I didn't get the expected results in validation. 
What's more, I notice that the reconstruct operation needs the current seed and PrgArrayDesc arrays. What is the relation between the PRG arrays and the reconstructed r0, rs? If the secret I want to reconstruct is related to a complex combination of different arrays which are not stored in a PrgArrayDesc array. Do I need to do extra efforts to copy the elements in different arrays to a new PrgArrayDesc array?

**Comment by rivertalk** [comment]
Hi, thanks for the detailed description.

> I used to think the c of Rank 1 adding the adjusted c of Rank 0 is the original multiplication result of a and b of Rank 1

It seems your assumption is almost correct. Suppose A locally sample (a0, b0, c0), B locally sample (a1, b1, c1), apparently, (a0+a1) * (b0+b1) != (c0+c1), here the "adjust" adjusts c0 to c0' so that  (a0+a1) * (b0+b1) != (c0'+c1), that is
 
```
c0' = (a0 + a1) * (b0 + b1) - c1
```

> What's more, I notice that the reconstruct operation needs the current seed and PrgArrayDesc arrays. What is the relation between the PRG arrays and the reconstructed r0, rs? If the secret I want to reconstruct is related to a complex combination of different arrays which are not stored in a PrgArrayDesc array. Do I need to do extra efforts to copy the elements in different arrays to a new PrgArrayDesc array?

First, the `Trusted first party` is not a SAFE setting, a safer setting is to use a `trusted third party`, the ttp first collect PRG seed from each parties, when each party sample randoms locally, the ttp `replay` the sample process (with each parties' PRG seed), then the ttp reconstruct it and compute the correct correlation (a * b = c). The last step is Party 0 `adjust` it's own c0 to c0', to satisfy the correlation.
