### ISSUE TITLE
Why use Concept-Based Polymorphism in type system

### ISSUE THREAD

**Issue by BeStrongok** [secretflow/spu#26]
Hi,
I read the implementation code of `Type`: https://github.com/secretflow/spu/blob/1c73e7a7390c022e11046eda762b43a6b8378be9/spu/core/type.h#L173
and find that this class can be treated as Adaptor of various type classes(e.g. VoidTy, PtTy, RingTy and so on), and they have same semantics, but no inheritance.
Why don't you directly use derived-based Polymorphism? In this way,`Type` is implemented as base class and have many virtual functions, various type classes can derive from the base class. A pointer to base class can call the function of derived class at the runtime.
I'm curious about the advantages of Concept-Based Polymorphism.
Thanks for your wonderful code.

**Comment by rivertalk** [comment]
Hi @BeStrongok , that's a good(hard) question :P

I tried to answer this but finally gave up, it's more clear to read sean parent's post.
https://sean-parent.stlab.cc/papers-and-presentations/#value-semantics-and-concept-based-polymorphism

From my experience, the most import reason is for the `value semantic`, that is, we don't have to use a pointer to the base type, and call `clone()` for every assignment. Since most of the time, the user (programmer working with type) does not need to know the detail of type, he/she only needs to deal with simple RAII semantics.

**Comment by BeStrongok** [comment]
> Hi @BeStrongok , that's a good(hard) question :P
> 
> I tried to answer this but finally gave up, it's more clear to read sean parent's post. https://sean-parent.stlab.cc/papers-and-presentations/#value-semantics-and-concept-based-polymorphism
> 
> From my experience, the most import reason is for the `value semantic`, that is, we don't have to use a pointer to the base type, and call `clone()` for every assignment. Since most of the time, the user (programmer working with type) does not need to know the detail of type, he/she only needs to deal with simple RAII semantics.

Thanks, i think your explanation is very clear. :)

**Comment by rivertalk** [comment]
Closing...
