### ISSUE TITLE
[Question]: Are the plaintexts passed to AddPlainInplace in NTT form?

### ISSUE THREAD

**Issue by maths644311798** [secretflow/spu#636]
### Issue Type

Usability

### Modules Involved

MPC protocol

### Have you reproduced the bug with SPU HEAD?

No

### Have you searched existing issues?

Yes

### SPU Version

commit id 774a9bfb4e123483aa8c09573b4028d07346d819 (HEAD -> main, tag: 0.9.0dev20240402, origin/main, origin/HEAD)

### OS Platform and Distribution

Ubuntu 20.04

### Python Version

3.10

### Compiler Version

gcc 13

### Current Behavior?

In mpc/cheetah/rlwe/utils.cc,  `void AddPlainInplace(RLWECt& ct, const RLWEPt& pt, const seal::SEALContext& context)`,
```
SPU_ENFORCE(ct.parms_id() == pt.parms_id());
```
The SEAL annnotation says "The parms_id must remain zero unless the plaintext polynomial is in NTT form".
Does it mean that the plaintext `pt` must be in NTT form?

### Standalone code to reproduce the issue

```Python
void AddPlainInplace(RLWECt& ct, const RLWEPt& pt,
                     const seal::SEALContext& context) {
  namespace sut = seal::util;
  SPU_ENFORCE(context.parameters_set());
  auto cntxt_data = context.get_context_data(ct.parms_id());
  SPU_ENFORCE(cntxt_data != nullptr);
  SPU_ENFORCE(ct.parms_id() == pt.parms_id());

  const auto& modulus = cntxt_data->parms().coeff_modulus();

  sut::RNSIter ct_iter(ct.data(0), ct.poly_modulus_degree());
  sut::ConstRNSIter pt_iter(pt.data(), ct.poly_modulus_degree());

  sut::add_poly_coeffmod(ct_iter, pt_iter, modulus.size(), modulus, ct_iter);
}
```

**Comment by anakinxc** [comment]
@fionser take a look?

**Comment by AdijeShen** [comment]
The answer is yes, you can see source code of seal encryptor: https://github.com/microsoft/SEAL/blob/206648d0e4634e5c61dcf9370676630268290b59/native/src/seal/encryptor.cpp#L203

the BFV plaintext **must not** be NTT form, but CKKS plaintext **must** be NTT form. when doing ct + pt operator, the pt should be in the same form of ct(being encrypted from an ntt-formed pt or non-ntt-formed pt)

In Cheetah protocol, some tricks are used such as using seal's ckks API to handle BFV plaintext (to avoid some check in seal's source code, and to avoid changing seal's source code).

To answer your question, the plaintext should be in NTT form since it uses CKKS api.

**Comment by fionser** [comment]
Actually, in `AddPlainInplace` and `SubPlainInpace` both of them work correctly for both NTT-formed and non-NTT formed input. We only need to take care the form of the ct and pt are aligned.
