### ISSUE TITLE
[Question]: overflow and underflow

### ISSUE THREAD

**Issue by linzzzzzz** [secretflow/spu#774]
### Feature Request Type

Documentation

### Have you searched existing issues?

Yes

### Is your feature request related to a problem?

1. Given a field type of `FM64` and a `fxp_fraction_bits = 24`. How to calculate (roughly) the smallest **positive** number it can handle without underflow, and the largest **positive** number it can handle without overflow? I'm using CHEETAH protocol.
2. What would be the impact if one number is a little bit smaller than "the smallest positive number without underflow" in question 1? Will the number be wrapped around to a very large positive number? or be truncated somehow? 
3. Similarly, what would be the impact if one number is a little bit larger than "the largest positive number without overflow" in question 1?

I have look around in documentation but could not find very relevant information. It would be very helpful if you could help provide some guidance. Thank you in advance!

### Describe features you want to add to SPU

--

### Describe features you want to add to SPU

--

**Comment by anakinxc** [comment]
> * Given a field type of `FM64` and a `fxp_fraction_bits = 24`. How to calculate (roughly) the smallest **positive** number it can handle without underflow, and the largest **positive** number it can handle without overflow? I'm using CHEETAH protocol.

Hi @linzzzzzz 

1. `FM64` means width = 64bits, with `fxp_fraction_bits = 24`, epsilon is 2^-24 = 5.96e-8, that is the smallest representable positive number. Since we already used 24bits for fraction part, we have 40bits for whole numbers. That gives us somewhere around 2^40 - 1 for largest whole numbers. 

But be aware of some operation requirements: mul/matmul will double the fraction bits during computation, that means only 16bits for whole numbers. Comparison/Truncation may requires k-2 bit is unused.

2&3. During floating-point to fixed-point encoding, we use `(intXX_t)(v * 2^fxp_bits)`, that means, fraction bits after scaling will be discarded and remaining whole number will be fitted into target integer, if fails, the behavior is undefined. During computation data's are just treated as integers, and follows int or uint overflow behaviors (some of those are UBs).

**Comment by anakinxc** [comment]
Hi @linzzzzzz 

I'll close this one, feel free to open new issue when other questions pop up.
