### ISSUE TITLE
Questions about the performance of serialization and deserialization using Protobuf

### ISSUE THREAD

**Issue by BeStrongok** [secretflow/spu#86]
Hi, 
I'm reading your wonderful code, and find that the binding of C++ secret values to Python object is implemented by Protobuf. 
The serialization and deserialization may cost hundreds of milliseconds, but i'm benchmarking the performance of SSLR model and  find that training speed is very fast.
So i'm curious about that is there any optimization in the serialization and deserialization?

**Comment by rivertalk** [comment]
Hi @BeStrongok, sorry for the late reply.

There is no special optimization on serialization/deserialization from C++ side, we just relying on protobuf default implementation.

But yes, theoretically, protobuf is not the best choice for large data serialization. Maybe does not hit the pain point due to SSLR's mini-batch mechinasm.

Have a nice day!

**Comment by anakinxc** [comment]
Another thing to notice here is ValueProto is relative simple in structure, which might help ser/deser performance.

But in general, as @rivertalk mentioned above, protobuf might not be the best choice, but it's far from become a major perf issue. 

But if you have a better choice in your mind, let us know.

Cheers

**Comment by BeStrongok** [comment]
Thanks for your reply! I'm looking for contributing a piece of code. :)
